const COUNTRY = process.env.NEXT_PUBLIC_COUNTRY || 'AZ';

// Theme colors per country - flag-inspired patriotic designs
const themes = {
  TR: {
    // Turkey - Red & White (Turkish flag)
    primary: 'from-red-600 to-red-700',
    primaryHover: 'hover:from-red-700 hover:to-red-800',
    accent: 'text-red-600',
    accentBg: 'bg-red-600',
    accentLight: 'bg-red-50',
    accentBorder: 'border-red-200',
    accentRing: 'focus:ring-red-500/20 focus:border-red-400',
    hero: 'from-red-700 via-red-600 to-red-500',
    heroGlow1: 'bg-white/10',
    heroGlow2: 'bg-red-300/20',
    logo: 'from-red-600 to-red-500',
    logoText: 'from-red-700 to-red-500',
    headerBorder: 'border-red-100',
    cityCardHover: 'hover:border-red-200',
    cityCardText: 'group-hover:text-red-600',
    langActive: 'text-red-600 bg-red-50',
    footerBg: 'bg-gray-900',
    badge: 'bg-red-500/10 text-red-200',
    statBg: 'bg-white/15',
    footerLinkActive: 'text-red-400',
  },
  AZ: {
    // Azerbaijan - Blue, Red, Green (flag)
    primary: 'from-blue-600 to-cyan-500',
    primaryHover: 'hover:from-blue-700 hover:to-cyan-600',
    accent: 'text-blue-600',
    accentBg: 'bg-blue-600',
    accentLight: 'bg-blue-50',
    accentBorder: 'border-blue-200',
    accentRing: 'focus:ring-blue-500/20 focus:border-blue-400',
    hero: 'from-blue-600 via-teal-500 to-green-500',
    heroGlow1: 'bg-white/10',
    heroGlow2: 'bg-green-300/20',
    logo: 'from-blue-500 to-green-500',
    logoText: 'from-blue-600 to-green-500',
    headerBorder: 'border-blue-100',
    cityCardHover: 'hover:border-blue-200',
    cityCardText: 'group-hover:text-blue-600',
    langActive: 'text-blue-600 bg-blue-50',
    footerBg: 'bg-gray-900',
    badge: 'bg-teal-500/10 text-teal-200',
    statBg: 'bg-white/15',
    footerLinkActive: 'text-blue-400',
  },
  KZ: {
    // Kazakhstan - Sky blue & Gold (flag)
    primary: 'from-sky-500 to-sky-600',
    primaryHover: 'hover:from-sky-600 hover:to-sky-700',
    accent: 'text-sky-600',
    accentBg: 'bg-sky-600',
    accentLight: 'bg-sky-50',
    accentBorder: 'border-sky-200',
    accentRing: 'focus:ring-sky-500/20 focus:border-sky-400',
    hero: 'from-sky-500 via-sky-400 to-yellow-400',
    heroGlow1: 'bg-yellow-300/15',
    heroGlow2: 'bg-sky-300/20',
    logo: 'from-sky-500 to-yellow-400',
    logoText: 'from-sky-600 to-yellow-500',
    headerBorder: 'border-sky-100',
    cityCardHover: 'hover:border-sky-200',
    cityCardText: 'group-hover:text-sky-600',
    langActive: 'text-sky-600 bg-sky-50',
    footerBg: 'bg-sky-950',
    badge: 'bg-yellow-400/15 text-yellow-200',
    statBg: 'bg-white/15',
    footerLinkActive: 'text-sky-400',
  },
  UZ: {
    // Uzbekistan - Blue, White, Green (flag)
    primary: 'from-blue-600 to-blue-700',
    primaryHover: 'hover:from-blue-700 hover:to-blue-800',
    accent: 'text-blue-600',
    accentBg: 'bg-blue-600',
    accentLight: 'bg-blue-50',
    accentBorder: 'border-blue-200',
    accentRing: 'focus:ring-blue-500/20 focus:border-blue-400',
    hero: 'from-blue-700 via-blue-500 to-emerald-500',
    heroGlow1: 'bg-white/10',
    heroGlow2: 'bg-emerald-300/20',
    logo: 'from-blue-600 to-emerald-500',
    logoText: 'from-blue-600 to-emerald-500',
    headerBorder: 'border-blue-100',
    cityCardHover: 'hover:border-blue-200',
    cityCardText: 'group-hover:text-blue-600',
    langActive: 'text-blue-600 bg-blue-50',
    footerBg: 'bg-gray-900',
    badge: 'bg-emerald-500/10 text-emerald-200',
    statBg: 'bg-white/15',
    footerLinkActive: 'text-blue-400',
  },
  TM: {
    // Turkmenistan - Green & Red
    primary: 'from-green-700 to-green-600',
    primaryHover: 'hover:from-green-800 hover:to-green-700',
    accent: 'text-green-700',
    accentBg: 'bg-green-700',
    accentLight: 'bg-green-50',
    accentBorder: 'border-green-200',
    accentRing: 'focus:ring-green-500/20 focus:border-green-400',
    hero: 'from-green-800 via-green-600 to-green-500',
    heroGlow1: 'bg-red-400/10',
    heroGlow2: 'bg-green-300/20',
    logo: 'from-green-600 to-green-500',
    logoText: 'from-green-700 to-green-500',
    headerBorder: 'border-green-100',
    cityCardHover: 'hover:border-green-200',
    cityCardText: 'group-hover:text-green-700',
    langActive: 'text-green-700 bg-green-50',
    footerBg: 'bg-green-950',
    badge: 'bg-green-500/10 text-green-200',
    statBg: 'bg-white/15',
    footerLinkActive: 'text-green-400',
  },
  KG: {
    // Kyrgyzstan - Red & Yellow
    primary: 'from-red-600 to-red-500',
    primaryHover: 'hover:from-red-700 hover:to-red-600',
    accent: 'text-red-600',
    accentBg: 'bg-red-600',
    accentLight: 'bg-red-50',
    accentBorder: 'border-red-200',
    accentRing: 'focus:ring-red-500/20 focus:border-red-400',
    hero: 'from-red-700 via-red-500 to-yellow-500',
    heroGlow1: 'bg-yellow-300/15',
    heroGlow2: 'bg-red-300/20',
    logo: 'from-red-500 to-yellow-500',
    logoText: 'from-red-600 to-yellow-500',
    headerBorder: 'border-red-100',
    cityCardHover: 'hover:border-red-200',
    cityCardText: 'group-hover:text-red-600',
    langActive: 'text-red-600 bg-red-50',
    footerBg: 'bg-gray-900',
    badge: 'bg-yellow-400/15 text-yellow-200',
    statBg: 'bg-white/15',
    footerLinkActive: 'text-red-400',
  },
  TJ: {
    // Tajikistan - Red, White, Green
    primary: 'from-red-600 to-green-600',
    primaryHover: 'hover:from-red-700 hover:to-green-700',
    accent: 'text-red-600',
    accentBg: 'bg-red-600',
    accentLight: 'bg-red-50',
    accentBorder: 'border-red-200',
    accentRing: 'focus:ring-red-500/20 focus:border-red-400',
    hero: 'from-red-600 via-white to-green-600',
    heroGlow1: 'bg-white/10',
    heroGlow2: 'bg-green-300/20',
    logo: 'from-red-500 to-green-500',
    logoText: 'from-red-600 to-green-500',
    headerBorder: 'border-red-100',
    cityCardHover: 'hover:border-red-200',
    cityCardText: 'group-hover:text-red-600',
    langActive: 'text-red-600 bg-red-50',
    footerBg: 'bg-gray-900',
    badge: 'bg-green-500/10 text-green-200',
    statBg: 'bg-white/15',
    footerLinkActive: 'text-red-400',
  },
};

const configs = {
  TR: {
    code: 'TR',
    domain: 'havacast.com.tr',
    locales: ['tr', 'en'],
    defaultLocale: 'tr',
    capital: 'istanbul',
    currency: 'TRY',
    siteName: 'HavaDurumu',
    theme: themes.TR,
    siteSlogan: {
      tr: "Türkiye'nin en doğru hava tahmini",
      en: 'The most accurate weather forecast in Turkey',
    },
    seoTitle: {
      tr: "Hava Durumu - Türkiye | HavaCast",
      en: 'Weather Forecast - Turkey | HavaCast',
    },
    seoDescription: {
      tr: "Türkiye şehirleri için en doğru hava durumu tahmini. İstanbul, Ankara, İzmir ve diğer şehirlerde sıcaklık, nem ve rüzgar bilgisi.",
      en: 'Accurate weather forecast for Turkey cities. Check temperature, humidity and wind in Istanbul, Ankara, Izmir and other cities.',
    },
    seoContent: {
      tr: [
        "HavaCast — Türkiye'nin en güvenilir hava durumu servisidir. Ülkenin tüm şehirleri için doğru hava durumu verileri sunuyoruz.",
        "Servisimiz her saat güncellenir. İstanbul, Ankara, İzmir, Bursa, Antalya, Adana, Konya, Gaziantep ve diğer şehirlerde hava durumunu takip edin.",
        'Sıcaklık, nem, rüzgar hızı ve yönü, atmosfer basıncı, gün doğumu ve batımı — tüm bunları HavaCast\'ta bulabilirsiniz.',
      ],
      en: [
        'HavaCast is the most reliable weather forecast service in Turkey. We provide accurate weather data for all cities across the country.',
        'Our service updates every hour. Track the weather in Istanbul, Ankara, Izmir, Bursa, Antalya, Adana, Konya and Gaziantep.',
        'Temperature, humidity, wind speed and direction, atmospheric pressure, sunrise and sunset — find it all on HavaCast.',
      ],
    },
  },
  AZ: {
    code: 'AZ',
    domain: 'havacast.az',
    locales: ['az', 'ru', 'en'],
    defaultLocale: 'az',
    capital: 'baku',
    currency: 'AZN',
    siteName: 'HavaProqnozu',
    theme: themes.AZ,
    siteSlogan: {
      az: "Azərbaycanın ən dəqiq hava proqnozu",
      ru: 'Самый точный прогноз погоды в Азербайджане',
      en: 'The most accurate weather forecast in Azerbaijan',
    },
    seoTitle: {
      az: 'Hava proqnozu - Azərbaycan | HavaCast',
      ru: 'Прогноз погоды - Азербайджан | HavaCast',
      en: 'Weather Forecast - Azerbaijan | HavaCast',
    },
    seoDescription: {
      az: 'Azərbaycan şəhərləri üçün dəqiq hava proqnozu. Bakı, Gəncə, Sumqayıt və digər şəhərlərdə temperaturu, rütubəti və küləyi öyrənin.',
      ru: 'Точный прогноз погоды для городов Азербайджана. Узнайте температуру, влажность и ветер в Баку, Гяндже, Сумгаите и других городах.',
      en: 'Accurate weather forecast for Azerbaijan cities. Check temperature, humidity and wind in Baku, Ganja, Sumgait and other cities.',
    },
    seoContent: {
      az: [
        'HavaCast — Azərbaycanın ən etibarlı hava proqnozu xidmətidir. Biz ölkənin bütün şəhərləri üçün dəqiq hava məlumatları təqdim edirik.',
        'Xidmətimiz hər saat yenilənir. Bakı, Gəncə, Sumqayıt, Mingəçevir, Lənkəran, Şirvan, Naxçıvan, Şəki və digər şəhərlərdə havanı izləyin.',
      ],
      ru: [
        'HavaCast — самый надежный сервис прогноза погоды в Азербайджане. Мы предоставляем точные данные о погоде для всех городов страны.',
        'Наш сервис обновляется каждый час. Следите за погодой в Баку, Гяндже, Сумгаите, Мингечевире, Ленкорани и Шеки.',
      ],
      en: [
        'HavaCast is the most reliable weather forecast service in Azerbaijan. We provide accurate weather data for all cities across the country.',
        'Our service updates every hour. Track the weather in Baku, Ganja, Sumgait, Mingachevir, Lankaran and Sheki.',
      ],
    },
  },
  KZ: {
    code: 'KZ', domain: 'havacast.kz', locales: ['kk', 'ru', 'en'], defaultLocale: 'ru', capital: 'astana', currency: 'KZT', siteName: 'AuaRaiy', theme: themes.KZ,
    siteSlogan: { kk: 'Қазақстанның ең дәл ауа райы болжамы', ru: 'Самый точный прогноз погоды в Казахстане', en: 'The most accurate weather forecast in Kazakhstan' },
    seoTitle: { kk: 'Ауа райы болжамы - Қазақстан | HavaCast', ru: 'Прогноз погоды - Казахстан | HavaCast', en: 'Weather Forecast - Kazakhstan | HavaCast' },
    seoDescription: { kk: 'Қазақстан қалалары үшін дәл ауа райы болжамы.', ru: 'Точный прогноз погоды для городов Казахстана.', en: 'Accurate weather forecast for Kazakhstan cities.' },
    seoContent: { kk: ['HavaCast — Қазақстанның ең сенімді ауа райы болжамы қызметі.'], ru: ['HavaCast — самый надежный сервис прогноза погоды в Казахстане.'], en: ['HavaCast is the most reliable weather forecast service in Kazakhstan.'] },
  },
  UZ: {
    code: 'UZ', domain: 'havacast.uz', locales: ['ru', 'en'], defaultLocale: 'ru', capital: 'tashkent', currency: 'UZS', siteName: 'ObHavo', theme: themes.UZ,
    siteSlogan: { ru: 'Самый точный прогноз погоды в Узбекистане', en: 'The most accurate weather forecast in Uzbekistan' },
    seoTitle: { ru: 'Прогноз погоды - Узбекистан | HavaCast', en: 'Weather Forecast - Uzbekistan | HavaCast' },
    seoDescription: { ru: 'Точный прогноз погоды для городов Узбекистана.', en: 'Accurate weather forecast for Uzbekistan cities.' },
    seoContent: { ru: ['HavaCast — сервис прогноза погоды в Узбекистане.'], en: ['HavaCast — weather forecast service in Uzbekistan.'] },
  },
  TM: {
    code: 'TM', domain: 'havacast.tm', locales: ['ru', 'en'], defaultLocale: 'ru', capital: 'ashgabat', currency: 'TMT', siteName: 'HowaBolcagy', theme: themes.TM,
    siteSlogan: { ru: 'Прогноз погоды в Туркменистане', en: 'Weather forecast in Turkmenistan' },
    seoTitle: { ru: 'Прогноз погоды - Туркменистан | HavaCast', en: 'Weather Forecast - Turkmenistan | HavaCast' },
    seoDescription: { ru: 'Точный прогноз погоды для городов Туркменистана.', en: 'Accurate weather forecast for Turkmenistan cities.' },
    seoContent: { ru: ['HavaCast — сервис прогноза погоды в Туркменистане.'], en: ['HavaCast — weather forecast service in Turkmenistan.'] },
  },
  KG: {
    code: 'KG', domain: 'havacast.kg', locales: ['ru', 'en'], defaultLocale: 'ru', capital: 'bishkek', currency: 'KGS', siteName: 'AbaIyigi', theme: themes.KG,
    siteSlogan: { ru: 'Прогноз погоды в Кыргызстане', en: 'Weather forecast in Kyrgyzstan' },
    seoTitle: { ru: 'Прогноз погоды - Кыргызстан | HavaCast', en: 'Weather Forecast - Kyrgyzstan | HavaCast' },
    seoDescription: { ru: 'Точный прогноз погоды для городов Кыргызстана.', en: 'Accurate weather forecast for Kyrgyzstan cities.' },
    seoContent: { ru: ['HavaCast — сервис прогноза погоды в Кыргызстане.'], en: ['HavaCast — weather forecast service in Kyrgyzstan.'] },
  },
  TJ: {
    code: 'TJ', domain: 'havacast.tj', locales: ['ru', 'en'], defaultLocale: 'ru', capital: 'dushanbe', currency: 'TJS', siteName: 'ObuHavo', theme: themes.TJ,
    siteSlogan: { ru: 'Прогноз погоды в Таджикистане', en: 'Weather forecast in Tajikistan' },
    seoTitle: { ru: 'Прогноз погоды - Таджикистан | HavaCast', en: 'Weather Forecast - Tajikistan | HavaCast' },
    seoDescription: { ru: 'Точный прогноз погоды для городов Таджикистана.', en: 'Accurate weather forecast for Tajikistan cities.' },
    seoContent: { ru: ['HavaCast — сервис прогноза погоды в Таджикистане.'], en: ['HavaCast — weather forecast service in Tajikistan.'] },
  },
};

export function getCountryConfig() {
  return configs[COUNTRY] || configs.AZ;
}

export function getCountryCode() {
  return COUNTRY;
}

export function getTheme() {
  return (configs[COUNTRY] || configs.AZ).theme;
}
