name: cd.yaml
on:
  push:
    branches:
      - main
jobs:
  getCode:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd /var/www/weather
            git pull
            if git diff HEAD~1 --name-only | grep -q "^frontend/"; then                                                                                    
              bash build-all.sh
            fi 
            pm2 restart all
            pm2 save
